name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "152d3f78-ea78-4da3-ab43-4338a001376c"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "88a93c8ef6144036813a37f098980ff9"
#preview_id = ""

#[[r2_buckets]]
#binding = "NOTES_R2_BUCKET"
#bucket_name = ""
#preview_bucket_name = "notes-files-preview"
